# Generated by Django 5.2.7 on 2025-11-02 05:41

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('memory_type', models.CharField(choices=[('short_term', 'Short Term'), ('long_term', 'Long Term'), ('personal', 'Personal'), ('conversation', 'Conversation')], max_length=20)),
                ('content', models.TextField()),
                ('embedding', models.BinaryField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('importance_score', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('accessed_count', models.IntegerField(default=0)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'memory_entries',
                'ordering': ['-importance_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemoryAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('read', 'Read'), ('update', 'Update'), ('recall', 'Recall'), ('search', 'Search')], max_length=20)),
                ('query_context', models.TextField(blank=True)),
                ('relevance_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='memory.memoryentry')),
            ],
            options={
                'db_table': 'memory_access_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_retention_days', models.IntegerField(default=30)),
                ('max_short_term_memories', models.IntegerField(default=100)),
                ('max_long_term_memories', models.IntegerField(default=1000)),
                ('auto_cleanup_enabled', models.BooleanField(default=True)),
                ('learning_rate', models.FloatField(default=0.7, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_preferences',
            },
        ),
        migrations.AddIndex(
            model_name='memoryentry',
            index=models.Index(fields=['user', 'memory_type'], name='memory_entr_user_id_565a4b_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryentry',
            index=models.Index(fields=['user', 'created_at'], name='memory_entr_user_id_e12c35_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryentry',
            index=models.Index(fields=['user', 'importance_score'], name='memory_entr_user_id_ab1300_idx'),
        ),
    ]
